(TeX-add-style-hook
 "st-manifolds"
 (lambda ()
   (TeX-add-symbols
    "ellipseA"
    "ellipseB"
    "dist"
    "scl")
   (LaTeX-add-labels
    "fig:mf-torus-pU"
    "fig:mf-torus-chart"
    "fig:mf-closed-line-3D"
    "fig:mf-closed-line-3D-chart"
    "fig:mf-three-lines"
    "fig:mf-three-lines-pU"
    "fig:mf-three-lines-invertible-map"
    "fig:mf-three-lines-wrong-map"
    "fig:mf-dbrane-string"
    "fig:mf-cartesian-chart-map-example"
    "fig:mf-polar-chart-map-example"
    "fig:mf-chart-transition-maps-one"
    "fig:mf-chart-transition-maps-two"
    "fig:mf-curve-chart"
    "eq:mf-chart-map-xgamma"
    "eq:mf-chart-maps-x-y-continuity"
    "eq:mf-chart-maps-x-y-differentiability"
    "fig:mf-curve-failed-differentiation"))
 :latex)

